### PR TITLE
Match falcon urls that don't have /s/0

### PR DESCRIPTION
**Pull request by adgad**
/cc @aintgoin2goa 

From the tweet: https://mobile.twitter.com/rkapfrance/status/581347891484164096

### CODE REVIEW

**Comment by aintgoin2goa** [comment]
:+1:  (Once the build passes)

**Comment by aintgoin2goa** [comment]
You'll need to do a release and update next-redirector

**Comment by aintgoin2goa** [comment]
oh, just saw you're ill - don't worry I'll take it from here

**Comment by adgad** [comment]
cheers :)

**Pull request merged**
